REM   Script: PKG_PROFESSOR
REM   Atividade da matéria Gerenciamento de Banco de Dados.

CREATE OR REPLACE PACKAGE PKG_ALUNO IS 
  PROCEDURE EXCLUIR_ALUNO (P_ID_ALUNO IN NUMBER); 
END PKG_ALUNO; 
/

CREATE OR REPLACE PACKAGE BODY PKG_ALUNO IS 
  PROCEDURE EXCLUIR_ALUNO (P_ID_ALUNO IN NUMBER) IS 
  BEGIN 
    DELETE FROM MATRICULAS WHERE ID_ALUNO = P_ID_ALUNO; 
    DELETE FROM ALUNOS WHERE ID = P_ID_ALUNO; 
  END EXCLUIR_ALUNO; 
END PKG_ALUNO; 
/

CREATE OR REPLACE PACKAGE PKG_ALUNO IS 
  PROCEDURE EXCLUIR_ALUNO (P_ID_ALUNO IN NUMBER); 
END PKG_ALUNO; 
/

CREATE OR REPLACE PACKAGE BODY PKG_ALUNO IS 
  PROCEDURE EXCLUIR_ALUNO (P_ID_ALUNO IN NUMBER) IS 
  BEGIN 
    DELETE FROM MATRICULAS WHERE ID_ALUNO = P_ID_ALUNO; 
    DELETE FROM ALUNOS WHERE ID = P_ID_ALUNO; 
  END EXCLUIR_ALUNO; 
END PKG_ALUNO; 
/

DECLARE 
  CURSOR C_ALUNOS_MAIORES_18 IS 
    SELECT NOME, DATA_NASCIMENTO 
    FROM ALUNOS 
    WHERE FLOOR(MONTHS_BETWEEN(SYSDATE, DATA_NASCIMENTO) / 12) > 18; 
BEGIN 
  FOR R_ALUNOS IN C_ALUNOS_MAIORES_18 LOOP 
    DBMS_OUTPUT.PUT_LINE('Nome: ' || R_ALUNOS.NOME || ', Data de Nascimento: ' || R_ALUNOS.DATA_NASCIMENTO); 
  END LOOP; 
END; 
/

DECLARE 
  CURSOR C_ALUNOS_POR_CURSO (P_ID_CURSO IN NUMBER) IS 
    SELECT NOME 
    FROM ALUNOS A 
    JOIN MATRICULAS M ON A.ID = M.ID_ALUNO 
    WHERE M.ID_CURSO = P_ID_CURSO; 
BEGIN 
  FOR R_ALUNOS IN C_ALUNOS_POR_CURSO(1) LOOP -- Substitua '1' pelo ID do curso desejado 
    DBMS_OUTPUT.PUT_LINE('Nome: ' || R_ALUNOS.NOME); 
  END LOOP; 
END; 
/

CREATE OR REPLACE PACKAGE PKG_PROFESSOR IS 
  CURSOR C_TOTAL_TURMAS_PROFESSOR; 
END PKG_PROFESSOR; 
/

CREATE OR REPLACE PACKAGE BODY PKG_PROFESSOR IS 
  CURSOR C_TOTAL_TURMAS_PROFESSOR IS 
    SELECT P.NOME, COUNT(T.ID) AS TOTAL_TURMAS 
    FROM PROFESSORES P 
    JOIN TURMAS T ON P.ID = T.ID_PROFESSOR 
    GROUP BY P.NOME 
    HAVING COUNT(T.ID) > 1; 
END PKG_PROFESSOR; 
/

CREATE OR REPLACE PACKAGE PKG_PROFESSOR IS 
  FUNCTION TOTAL_TURMAS_PROFESSOR(P_ID_PROFESSOR IN NUMBER) RETURN NUMBER; 
END PKG_PROFESSOR; 
/

CREATE OR REPLACE PACKAGE BODY PKG_PROFESSOR IS 
  FUNCTION TOTAL_TURMAS_PROFESSOR(P_ID_PROFESSOR IN NUMBER) RETURN NUMBER IS 
    V_TOTAL_TURMAS NUMBER; 
  BEGIN 
    SELECT COUNT(*) 
    INTO V_TOTAL_TURMAS 
    FROM TURMAS 
    WHERE ID_PROFESSOR = P_ID_PROFESSOR; 
    RETURN V_TOTAL_TURMAS; 
  END TOTAL_TURMAS_PROFESSOR; 
END PKG_PROFESSOR; 
/

CREATE OR REPLACE PACKAGE PKG_PROFESSOR IS 
  FUNCTION PROFESSOR_DISCIPLINA(P_ID_DISCIPLINA IN NUMBER) RETURN VARCHAR2; 
END PKG_PROFESSOR; 
/

CREATE OR REPLACE PACKAGE BODY PKG_PROFESSOR IS 
  FUNCTION PROFESSOR_DISCIPLINA(P_ID_DISCIPLINA IN NUMBER) RETURN VARCHAR2 IS 
    V_NOME_PROFESSOR VARCHAR2(100); 
  BEGIN 
    SELECT P.NOME 
    INTO V_NOME_PROFESSOR 
    FROM PROFESSORES P 
    JOIN DISCIPLINAS D ON P.ID = D.ID_PROFESSOR 
    WHERE D.ID = P_ID_DISCIPLINA; 
    RETURN V_NOME_PROFESSOR; 
  END PROFESSOR_DISCIPLINA; 
END PKG_PROFESSOR; 
/

